[theme]
theme = "slick"
[theme.overrides]
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"

[icons]
icons = "awesome6"
[icons.overrides]
cpu = "  "
memory_mem = "  "
memory_swap = "  "

[[block]]
block = "custom"
command = "echo  $(hostname)"
interval = "once"

[[block]]
block = "cpu"
interval = 10
format = " $icon $utilization "

[[block]]
block = "load"
interval = 10
format = " $icon $1m.eng(w:4) $5m.eng(w:4) $15m.eng(w:4) "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
interval = 10
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "temperature"
interval = 10
idle = 50
chip = "coretemp-isa-0000"
format = " $icon $max "

[[block]]
block = "custom"
command = "echo  $(i8kctl speed | cut -d' ' -f2) RPM"
interval = 10

[[block]]
block = "docker"
interval = 120
format = " $icon $running "

[[block]]
block = "net"
device = "wlp[0-9]+s0"
interval = 30
format = " $icon {$signal_strength $ssid $frequency|} $device "
missing_format = ""

[[block]]
block = "net"
device = "enp[0-9]{2}s[0-9](0f0)*u[0-9]u[0-9]"
interval = 60
missing_format = ""

[[block]]
block = "net"
device = "tun0"
interval = 5
missing_format = ""

[[block]]
block = "bluetooth"
mac = "38:18:4C:3E:95:E8"
disconnected_format = "📶"

[[block]]
block = "sound"
step_width = 5
show_volume_when_muted = false

[[block]]
block = "sound"
driver = "alsa"
name = "Capture"
step_width = 5
show_volume_when_muted = false

[[block]]
block = "battery"
format = " $icon $percentage $time "
interval = 60
device = "BAT0"
driver = "sysfs"

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R') "

[[block]]
block = "custom"
command = "~/.i3/show-layout.sh"
interval = 3
