theme = "bad-wolf"

[icons]
name = "awesome"
[icons.overrides]
cpu = "  "
memory_mem = "  "
memory_swap = "  "

[[block]]
block = "cpu"
interval = 5
format = "{utilization}% {frequency} GHz"

[[block]]
block = "load"
interval = 1
format = "{1m} {5m} {15m}"

[[block]]
block = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "docker"
interval = 60
format = "{running}"

[[block]]
block = "net"
device = "wlp58s0"
hide_missing = true
hide_inactive = true
ssid = true
signal_strength = true
speed_up = false
speed_down = false
ip = false
interval = 5

[[block]]
block = "net"
device = "enp0s20f0u2u3"
hide_missing = true
hide_inactive = true
signal_strength = false
speed_up = false
speed_down = false
ip = false
interval = 60

[[block]]
block = "net"
device = "tun0"
hide_missing = true
hide_inactive = true
signal_strength = false
speed_up = false
speed_down = false
ip = false
interval = 5

[[block]]
block = "music"
player = "spotify"
buttons = ["play"]
on_collapsed_click = "spotify"
marquee_speed = 1

[[block]]
block = "bluetooth"
mac = "38:18:4C:3E:95:E8"

[[block]]
block = "sound"
step_width = 5
show_volume_when_muted = false

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time} {power}"

[[block]]
block = "time"
interval = 60
format = "%F %R"
timezone = "Europe/Lisbon"
