[theme]
name = "slick"
[theme.overrides]
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"

[icons]
name = "awesome"
[icons.overrides]
cpu = "  "
memory_mem = "  "
memory_swap = "  "

[[block]]
block = "custom"
command = "echo  $(hostname)"
interval = 3600

[[block]]
block = "cpu"
interval = 10
format = "{utilization} {frequency}"

[[block]]
block = "load"
interval = 10
format = "{1m} {5m} {15m}"

[[block]]
block = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
display_type = "memory"
icons = true
clickable = true
interval = 10
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "temperature"
interval = 30
idle = 50
collapsed = false
chip = "coretemp-isa-0000"
format = "  {max}°"

[[block]]
block = "temperature"
interval = 30
idle = 50
collapsed = false
chip = "nvme-pci-7100"
format = "  {max}°"

[[block]]
block = "docker"
interval = 120
format = "{running}"

[[block]]
block = "net"
device = "wlp58s0"
hide_missing = true
hide_inactive = true
ssid = true
signal_strength = true
speed_up = false
speed_down = false
ip = false
interval = 30

[[block]]
block = "net"
device = "wlp2s0"
hide_missing = true
hide_inactive = true
ssid = true
signal_strength = true
speed_up = false
speed_down = false
ip = false
interval = 30

[[block]]
block = "net"
device = "enp0s20f0u2u3"
hide_missing = true
hide_inactive = true
signal_strength = false
speed_up = false
speed_down = false
ip = false
interval = 60

[[block]]
block = "net"
device = "enp57s0u1u3"
hide_missing = true
hide_inactive = true
signal_strength = false
speed_up = false
speed_down = false
ip = false
interval = 60

[[block]]
block = "net"
device = "enp0s20f0u1u3"
hide_missing = true
hide_inactive = true
signal_strength = false
speed_up = false
speed_down = false
ip = false
interval = 60

[[block]]
block = "net"
device = "proton0"
hide_missing = true
hide_inactive = true
signal_strength = false
speed_up = false
speed_down = false
ip = false
interval = 5

[[block]]
block = "bluetooth"
mac = "38:18:4C:3E:95:E8"

[[block]]
block = "sound"
step_width = 5
show_volume_when_muted = false

[[block]]
block = "sound"
driver = "alsa"
name = "Capture"
step_width = 5
show_volume_when_muted = false

[[block]]
block = "battery"
format = "{percentage}% {time} {power}w"
interval = 60

[[block]]
block = "custom"
interval = 60
command = "echo  $(date +%F)"

[[block]]
block = "custom"
interval = 20
command = "echo UK $(date +%R)"

[[block]]
block = "custom"
interval = 20
command = "echo JP $(TZ='Japan' date +%R)"

[[block]]
block = "custom"
command = "~/.i3/show-layout.sh"
interval = 3
